var num1 = 11;
var num2 = 12;
var op1 = "addition";
var op2 = "subtraction";
var op3 = "multi";
var op4 = "division";
console.log("Addition is: " + (num1 + num2));
console.log("Subtraction is: " + (num1 - num2));
console.log("Multiplication is: " + (num1 * num2));
console.log("Division is: " + (num1 / num2));
