// seeing the world: think of at least five places in the world you'd like to visit:....
// Store the location in an arary Make sure the an array are not in the alphabetical order.......
// Print yor an array in original order.......
var __spreadArray = (this && this.__spreadArray) || function (to, from, pack) {
    if (pack || arguments.length === 2) for (var i = 0, l = from.length, ar; i < l; i++) {
        if (ar || !(i in from)) {
            if (!ar) ar = Array.prototype.slice.call(from, 0, i);
            ar[i] = from[i];
        }
    }
    return to.concat(ar || Array.prototype.slice.call(from));
};
var places = ["Karachi", "Hyderabad", "Sukkur", "Lahore", "Islamabad"];
console.log("Original " + places);
// Print your array in orginal in alphabetical order without modifying the actual list.......
console.log("copy" + __spreadArray([], places, true).sort());
// Show that your list is still in its original order by printing it....
console.log("original :" + places);
// Print your array in reverse alphatbetical order without changing th eorder of the original list......
console.log("copy " + __spreadArray([], places, true).sort().reverse());
// Show that your list is still in its original order by printing it again...
console.log("copy " + __spreadArray([], places, true).sort().reverse());
// Reverse the order of your list .Print the array to show that its order has changed........
console.log("original " + places.sort());
// Reerse the order of your list. Print the list to show its backto its original order
console.log("original " + places.sort().reverse());
